### PR TITLE
fix: #233 Allow @JsonIgnoreProperties and @JsonUnwrapped to work together

### PR DESCRIPTION
**Pull request by edeesis**

### CODE REVIEW

**Comment by alvarosanchez** [comment]
There seems to be a compilation error. Could you please fix that?

**Comment by edeesis** [comment]
Ah thanks! I was cleaning up some import changes that were automatically applied by my IDE (import java.util.*) and forgot to include that import.

**Comment by edeesis** [comment]
I'm not sure what to do about the Static Analysis build failure

**Comment by graemerocher** [comment]
Thanks for the contribution!

**Pull request merged**
