### PR TITLE
Serialization of AWS events

### PR DESCRIPTION
**Pull request by sdelamo**
Includes a module to provide Serde configuration for [AWS Lambda Events](https://github.com/aws/aws-lambda-java-libs/tree/master/aws-lambda-java-events) POJOs.

### CODE REVIEW

**Comment by graemerocher** [comment]
@sdelamo the latest PR from @dstepanov might help with the AWS case https://github.com/micronaut-projects/micronaut-serialization/pull/78

**Comment by dstepanov** [comment]
@sdelamo What problem do you have?

**Comment by sdelamo** [comment]
@dstepanov This PR contains a test annotated with `PendingFeature`  to test serialization into a `SQSEvent` a POJO distributed by AWS Lambda events library. They ship POJOs and Mixins. 

I would like to be able to apply serialize to [SQSEvent](https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/SQSEvent.java) leveraging [SQSEventMixin](https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-serialization/src/main/java/com/amazonaws/services/lambda/runtime/serialization/events/mixins/SQSEventMixin.java)

Do you know how could I achieve that?

**Comment by sdelamo** [comment]
@dstepanov do you have any feedback about this?

**Comment by dstepanov** [comment]
It might be possible to use `@SerdeImport` with a custom naming strategy that converts `records` to `Records` etc. The best way would be to support something like mixins with: `@SerdeImport(value=Xyz.class, mixin=XyzMixin.class)` WDYT @graemerocher? I think we already have some kind of annotation hierarchy, mixin would contribute the first place matched by the name of field/property/constructor parameter.

**Comment by graemerocher** [comment]
Sounds good

**Comment by graemerocher** [comment]
I will take a look at this

**Comment by graemerocher** [comment]
PR submitted with a solution for this https://github.com/micronaut-projects/micronaut-serialization/pull/102

**Comment by graemerocher** [comment]
FWIW I think this code belongs in the AWS module not here

**Comment by sdelamo** [comment]
I added the mixin as in @yawkat PR but the test is still failing. 

@yawkat any idea?

**Comment by yawkat** [comment]
im not sure, but the mixin being in a different jar that isnt covered by the annotation processor could be the problem

**Comment by graemerocher** [comment]
The reason this is failing is because AWS re-packages Jackson and the byte code the annotations are `com.amazonaws.lambda.thirdparty.com.fasterxml.jackson.annotation.JsonProperty` 😱

**Comment by yawkat** [comment]
🤦

**Comment by sdelamo** [comment]
> The reason this is failing is because AWS re-packages Jackson and the byte code the annotations are `com.amazonaws.lambda.thirdparty.com.fasterxml.jackson.annotation.JsonProperty` 😱

Should an annotation mapper which maps `@JsonProperty` to `com.fasterxml.jackson.annotation.JsonProperty` help?

**Comment by graemerocher** [comment]
See https://github.com/micronaut-projects/micronaut-serialization/pull/108

**Comment by sdelamo** [comment]
@yawkat and @graemerocher The `mixin` works great. 

`aws-events` library uses joda and it has fields of type `org.joda.time.DateTime`. 

They ship with two `com.fasterxml.jackson.databind.module.SimpleModule`

https://github.com/aws/aws-lambda-java-libs/tree/master/aws-lambda-java-serialization/src/main/java/com/amazonaws/services/lambda/runtime/serialization/events/modules

How could we handle this?

**Comment by graemerocher** [comment]
Add `Serializer` and `Deserializer`  beans (or a single bean of type `Serde`) for `DateTime`

**Comment by graemerocher** [comment]
I committed what you need to add

**Comment by sdelamo** [comment]
@graemerocher 

> FWIW I think this code belongs in the AWS module not here

I have moved it to aws https://github.com/micronaut-projects/micronaut-aws/pull/1264

**Pull request closed without merging**
