### PR TITLE
Add test for `@JsonProperty` annotation on enum constant level

### PR DESCRIPTION
**Pull request by altro3**
See: #503

### CODE REVIEW

**Comment by altro3** [comment]
@dstepanov Added test for this case. All works fine with databind

**Comment by dstepanov** [comment]
Please add this and other test as `@PendingFeature` so it can be merged

**Comment by altro3** [comment]
done

**Comment by dstepanov** [comment]
Can you please rebase it and check if it's working?

**Comment by altro3** [comment]
Yes, now all works fine. Just close this PR or merge?

**Comment by dstepanov** [comment]
We can have extra test

**Pull request merged**
