### PR TITLE
Enable native examples and the server TCK

### PR DESCRIPTION
**Pull request by dstepanov**

### CODE REVIEW

**Review by graemerocher — APPROVED** [review]

**Review by sdelamo — APPROVED** [review]

**Review by sdelamo — CHANGES_REQUESTED** [review]
native tests seems to fail

**Comment by dstepanov** [comment]
I had to disable the static test; it's also disabled in the servlet module.

**Comment by yawkat** [comment]
it seems like the build could be fixed to include the static resources

**Comment by dstepanov** [comment]
How?

**Review by sdelamo — APPROVED** [review]

**Pull request merged**
