### PR TITLE
Decoding an object to a string doesn't throw an exception

### LINKED ISSUE #441: Unable to bind form submission to method parameters
The following tests pass with `micronaut-jackson-databind`

```java
package temp;

import io.micronaut.context.annotation.Property;
import io.micronaut.context.annotation.Requires;
import io.micronaut.core.annotation.Introspected;
import io.micronaut.core.annotation.NonNull;
import io.micronaut.core.annotation.Nullable;
import io.micronaut.http.HttpRequest;
import io.micronaut.http.HttpStatus;
import io.micronaut.http.MediaType;
import io.micronaut.http.annotation.Body;
import io.micronaut.http.annotation.Consumes;
import io.micronaut.http.annotation.Controller;
import io.micronaut.http.annotation.Post;
import io.micronaut.http.annotation.Status;
import io.micronaut.http.client.BlockingHttpClient;
import io.micronaut.http.client.HttpClient;
import io.micronaut.http.client.annotation.Client;
import io.micronaut.http.uri.UriBuilder;
import io.micronaut.test.extensions.junit5.annotation.MicronautTest;
import org.junit.jupiter.api.Test;

import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;

@Property(name = "spec.name", value = "FormTest")
@MicronautTest
class FormTest {

    @Test
    void formWithPojoWorks(@Client("/")HttpClient httpClient) {
        BlockingHttpClient client = httpClient.toBlocking();
        assertDoesNotThrow(() -> client.exchange(formRequest("pojo")));
    }

    @Test
    void formWithMethodParamsWorks(@Client("/")HttpClient httpClient) {
        BlockingHttpClient client = httpClient.toBlocking();
        assertDoesNotThrow(() -> client.exchange(formRequest("methodparameter")));
    }

    private HttpRequest<?> formRequest(String path) {
        Map<String, String> form = Map.of("grant_type", "client_credentials");
        return HttpRequest.POST(UriBuilder.of("/token").path(path).build(), form)
            .contentType(MediaType.APPLICATION_FORM_URLENCODED);
    }

    @Requires(property = "spec.name", value = "FormTest")
    @Controller("/token")
    static class TokenController {

        @Consumes(MediaType.APPLICATION_FORM_URLENCODED)
        @Post("/pojo")
        @Status(HttpStatus.OK)
        void tokenPojo(@Body ClientCredentialsForm form) {
        }

        @Consumes(MediaType.APPLICATION_FORM_URLENCODED)
        @Post("/methodparameter")
        @Status(HttpStatus.OK)
        void tokenMethodParam(@NonNull String grant_type,
                   @Nullable String client_id,
                   @Nullable String client_secret) {
        }
    }

    @Introspected
    static class ClientCredentialsForm {

        @NonNull
        private final String grant_type;

        @Nullable
        private final String client_id;

        @Nullable
        private final String client_secret;

        public ClientCredentialsForm(@NonNull String grant_type, @Nullable String client_id, @Nullable String client_secret) {
            this.grant_type = grant_type;
            this.client_id = client_id;
            this.client_secret = client_secret;
        }

        @Nullable
        public String getGrant_type() {
            return grant_type;
        }

        @Nullable
        public String getClient_id() {
            return client_id;
        }

        @Nullable
        public String getClient_secret() {
            return client_secret;
        }
    }

}
```

with Micronaut Serialization the test with method parameters fails: 

```java
package example.form;

import io.micronaut.context.annotation.Property;
import io.micronaut.context.annotation.Requires;
import io.micronaut.core.annotation.NonNull;
import io.micronaut.core.annotation.Nullable;
import io.micronaut.http.HttpRequest;
import io.micronaut.http.HttpStatus;
import io.micronaut.http.MediaType;
import io.micronaut.http.annotation.Body;
import io.micronaut.http.annotation.Consumes;
import io.micronaut.http.annotation.Controller;
import io.micronaut.http.annotation.Post;
import io.micronaut.http.annotation.Status;
import io.micronaut.http.client.BlockingHttpClient;
import io.micronaut.http.client.HttpClient;
import io.micronaut.http.client.annotation.Client;
import io.micronaut.http.uri.UriBuilder;
import io.micronaut.serde.annotation.Serdeable;
import io.micronaut.test.extensions.junit5.annotation.MicronautTest;
import org.junit.jupiter.api.Test;

import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;

@Property(name = "spec.name", value = "FormTest")
@MicronautTest
class FormTest {

    @Test
    void formWithPojoWorks(@Client("/")HttpClient httpClient) {
        BlockingHttpClient client = httpClient.toBlocking();
        ✅assertDoesNotThrow(() -> client.exchange(formRequest("pojo")));
    }

    @Test
    void formWithMethodParamsWorks(@Client("/")HttpClient httpClient) {
        BlockingHttpClient client = httpClient.toBlocking();
       ❌  assertDoesNotThrow(() -> client.exchange(formRequest("methodparameter")));
    }

    private HttpRequest<?> formRequest(String path) {
        Map<String, String> form = Map.of("grant_type", "client_credentials");
        return HttpRequest.POST(UriBuilder.of("/token").path(path).build(), form)
            .contentType(MediaType.APPLICATION_FORM_URLENCODED);
    }

    @Requires(property = "spec.name", value = "FormTest")
    @Controller("/token")
    static class TokenController {

        @Consumes(MediaType.APPLICATION_FORM_URLENCODED)
        @Post("/pojo")
        @Status(HttpStatus.OK)
        void tokenPojo(@Body ClientCredentialsForm form) {
        }

        @Consumes(MediaType.APPLICATION_FORM_URLENCODED)
        @Post("/methodparameter")
        @Status(HttpStatus.OK)
        void tokenMethodParam(@NonNull String grant_type,
                              @Nullable String client_id,
                              @Nullable String client_secret) {
        }
    }

    @Serdeable
    static class ClientCredentialsForm {

        @NonNull
        private final String grant_type;

        @Nullable
        private final String client_id;

        @Nullable
        private final String client_secret;

        public ClientCredentialsForm(@NonNull String grant_type, @Nullable String client_id, @Nullable String client_secret) {
            this.grant_type = grant_type;
            this.client_id = client_id;
            this.client_secret = client_secret;
        }

        @Nullable
        public String getGrant_type() {
            return grant_type;
        }

        @Nullable
        public String getClient_id() {
            return client_id;
        }

        @Nullable
        public String getClient_secret() {
            return client_secret;
        }
    }

}
```

### PR DESCRIPTION
**Pull request by sdelamo**
Fixes #441

### CODE REVIEW

**Comment by sdelamo** [comment]
@yawkat I think this behaviour was broken between M1 and M4

**Comment by graemerocher** [comment]
@yawkat I did some investigation. Not sure if the issue is here or in core. From what I can tell for some reason the `UnmatchedRequestArgumentBinder` does this:

```java
   @Override
    public BindingResult<T> bindPostponed(ArgumentConversionContext<T> context, HttpRequest<?> request) {
        BindingResult<T> lastWithError = null;
        for (RequestArgumentBinder<Object> binder : stream().filter(binder -> (binder instanceof PostponedRequestArgumentBinder)).toList()) {
            BindingResult<?> result = binder.bind((ArgumentConversionContext<Object>) context, request);
 
```

Which ends up trying to convert the full map of parameters (this is a form submission) into a String via this converter:

```java
    protected TypeConverter<Map, Object> mapToObjectConverter() {
        return (map, targetType, context) -> {
            ArgumentConversionContext<Object> conversionContext;
            if (context instanceof ArgumentConversionContext) {
                conversionContext = (ArgumentConversionContext<Object>) context;
            } else {
                conversionContext = ConversionContext.of(targetType);
            }
            ArgumentBinder binder = this.beanPropertyBinder.get();
            ArgumentBinder.BindingResult result = binder.bind(conversionContext, correctKeys(map));
            return result.getValue();
        };
    }
```

Since Micronaut Serialization doesn't allow turning JSON objects into strings this returns `null` which results in a NPE :

```
06:40:32.695 [default-nioEventLoopGroup-1-3] ERROR i.m.http.server.RouteExecutor - Unexpected error occurred: null
java.lang.NullPointerException: null
	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
	at java.base/java.util.Optional.of(Optional.java:113)
	at io.micronaut.json.bind.JsonBeanPropertyBinder.lambda$bind$0(JsonBeanPropertyBinder.java:72)
	
```

The behaviour seems incorrect here, it is unclear why it is trying to bind the full body to one of the parameters

**Comment by yawkat** [comment]
@graemerocher it's a combination of core and serde i think. it's trying to bind the full map to the string parameter because of the `@Body` fallback that will be removed in https://github.com/micronaut-projects/micronaut-core/pull/9151/ . but this should still work fine usually–the serde bug is that this conversion does *not* fail due to incorrect null handling that is fixed by #425.

at least that was my impression when i looked at this in security, i will test it with #425 now.

**Comment by yawkat** [comment]
ah no, it is still broken with #425, i will fix it. the issue is that decodeStringNullable returns null when the token is START_OBJECT.

**Comment by yawkat** [comment]
the test looks broken, it does not use serde from the project, it uses M3.

**Comment by graemerocher** [comment]
I pushed a fix for the build

**Comment by yawkat** [comment]
thanks

**Review by graemerocher — APPROVED** [review]

**Pull request merged**
